all:
	@gcc -o unix_stream_server unix_stream_server.c
	@gcc -o unix_stream_client unix_stream_client.c
	@gcc -o unix_dgram_server unix_dgram_server.c
	@gcc -o unix_dgram_client unix_dgram_client.c

clean:
	@rm unix_stream_server
	@rm unix_stream_client
	@rm unix_dgram_server
	@rm unix_dgram_client
